// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa1iGllM1VPAnZZoZj_y1_GHJr_olg_Eo',
    appId: '1:378147682569:web:34b370af989233b940bbd8',
    messagingSenderId: '378147682569',
    projectId: 'admin-7595b',
    authDomain: 'admin-7595b.firebaseapp.com',
    storageBucket: 'admin-7595b.firebasestorage.app',
    measurementId: 'G-4Q132L0RPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_SnsfhXpszwhwsHLWgkYMSDvTjQUCCI',
    appId: '1:378147682569:android:c0f77b58aa9c3ec640bbd8',
    messagingSenderId: '378147682569',
    projectId: 'admin-7595b',
    storageBucket: 'admin-7595b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA11cKiGeiD4ad5FcnKG5gjZDjJbbhmCwE',
    appId: '1:378147682569:ios:c99c7a4c419ff6ae40bbd8',
    messagingSenderId: '378147682569',
    projectId: 'admin-7595b',
    storageBucket: 'admin-7595b.firebasestorage.app',
    iosBundleId: 'com.example.birdsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA11cKiGeiD4ad5FcnKG5gjZDjJbbhmCwE',
    appId: '1:378147682569:ios:c99c7a4c419ff6ae40bbd8',
    messagingSenderId: '378147682569',
    projectId: 'admin-7595b',
    storageBucket: 'admin-7595b.firebasestorage.app',
    iosBundleId: 'com.example.birdsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa1iGllM1VPAnZZoZj_y1_GHJr_olg_Eo',
    appId: '1:378147682569:web:ca00b6e9fd110fd040bbd8',
    messagingSenderId: '378147682569',
    projectId: 'admin-7595b',
    authDomain: 'admin-7595b.firebaseapp.com',
    storageBucket: 'admin-7595b.firebasestorage.app',
    measurementId: 'G-J7F8XKR435',
  );
}
